-- First, let's insert the admin user with email confirmation
INSERT INTO auth.users (
  id,
  aud,
  role,
  email,
  email_confirmed_at,
  phone_confirmed_at,
  confirmation_token,
  recovery_token,
  email_change_token_new,
  email_change,
  instance_id,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  last_sign_in_at,
  email_change_sent_at,
  banned_until,
  phone_change_token,
  phone_change,
  phone_change_sent_at,
  confirmed_at,
  email_change_confirm_status,
  encrypted_password
) VALUES (
  'c25a1c26-9e4b-4b8a-a6f1-0a1b2c3d4e5f',
  'authenticated',
  'authenticated', 
  'cezicolatecnologia@gmail.com',
  now(),
  null,
  '',
  '',
  '',
  '',
  '00000000-0000-0000-0000-000000000000',
  '{"provider": "email", "providers": ["email"]}',
  '{"first_name": "Admin", "last_name": "Matriz", "role": "root_account"}',
  false,
  now(),
  now(),
  null,
  null,
  null,
  '',
  '',
  null,
  now(),
  0,
  crypt('minebea640064', gen_salt('bf'))
) ON CONFLICT (email) DO UPDATE SET
  encrypted_password = crypt('minebea640064', gen_salt('bf')),
  email_confirmed_at = now(),
  confirmed_at = now(),
  updated_at = now(),
  raw_user_meta_data = '{"first_name": "Admin", "last_name": "Matriz", "role": "root_account"}';